runtime: python312
entrypoint: gunicorn backend.app:app
service: default

handlers:
  # Serve static files from the frontend build output (adjust path based on your build process)
  - url: /static
    static_dir: src/build/static

  # Handler for PDF uploads
  - url: /upload/(.+\.pdf)$
    script: backend.app:upload_file  # Assuming a function in app.py

  # Serve other static files (JSON, ICO, JS, TXT)
  - url: /(.*\.(json|ico|js|txt))
    static_files: dist/

  # Catches all unmatched requests and serves the frontend (adjust path based on your build process)
  - url: /.*
    static_files: src/build/index.html
