runtime: python312
entrypoint: gunicorn backend.app:app

handlers:
- url: /static
  static_dir: dist/static
- url: /(.*\.(json|ico|js|txt))
  static_files: dist/\1
  upload: dist/(.*\.(json|ico|js|txt))
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
- url: /upload
  script: backend.app:upload_file
