runtime: python312
entrypoint: gunicorn backend.app:app

handlers:
- url: /static
  static_dir: dist/static
- url: /(.*\.(json|ico|js|txt))
  static_files: dist/\1
  upload: dist/(.*\.(json|ico|js|txt))
- url: /.*  # Catches all unmatched requests (can be adjusted for frontend)
  static_files: dist/index.html
  upload: dist/index.html  # Optional for frontend uploads
- url: /upload/(.+\.pdf)$  # Handler for PDF uploads
  script: backend.app:handle_pdf_upload  # Assuming a function in app.py
