runtime: python312
entrypoint: gunicorn backend.app:app
service: default

# Cloud Build Step (for deployment)
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']
  dir: '.'  # Points to the root directory

handlers:
  # Serve static files from the frontend build output (adjust path based on your build process)
  - url: /static
    static_dir: src/build/static

  # Serve other static files (JSON, ICO, JS, TXT)
  - url: /(.*\.(json|ico|js|txt))
    static_files: dist/

  # Catches all unmatched requests and serves the frontend (adjust path based on your build process)
  - url: /.*
    static_files: src/build/index.html

  # Handler for PDF uploads using Cloud Storage
  - url: /upload/(.+\.pdf)$
    script: backend.app:handle_pdf_upload  # Assuming a function in app.py
