steps:
  # Install npm dependencies for the React app
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['install']
    dir: 'src'  # Change this to the directory containing your package.json if different

  # Build the React app using Vite
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'src'  # Vite will build the app according to its configuration

  # Install Python dependencies for the Flask app
  - name: 'python:3.9'
    entrypoint: 'pip'
    args: ['install', '-r', 'backend/requirements.txt']

  # Deploy the app to Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'backend/app.yaml']

options:
  logging: 'CLOUD_LOGGING_ONLY'
