steps:
  # Build the Python app
  - name: 'python:3.12'
    entrypoint: 'pip'
    args: ['install', '-r', 'backend/requirements.txt']

  # Build the React app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'src'

  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'src'

  # Deploy the application from the root where app.yaml is located
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'

timeout: '1600s'
options:
  logging: 'CLOUD_LOGGING_ONLY'
