steps:
  # Install npm dependencies for the React app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'src'  

  # Build the React app using Vite
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'src'  

  # Install Python dependencies for the Flask app
  - name: 'python:3.12'
    entrypoint: 'pip'
    args: ['install', '-r', 'backend/requirements.txt']

  # Deploy the app to Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']

options:
  logging: 'CLOUD_LOGGING_ONLY'
