steps:
  # Step 1: Create a virtual environment and install dependencies
  - name: 'python:3.12'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        python3 -m venv venv && \
        source venv/bin/activate && \
        pip install -r backend/requirements.txt && \
        pwd && \
        ls -l

  # 2. Install Python dependencies within the virtual environment
  - name: 'python:3.12'
    entrypoint: 'pip'
    args: ['install', '-r', 'backend/requirements.txt']

  # 3. Build the React app (unchanged)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'src'

  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'src'

  # 4. Deploy the App Engine application
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']

options:
  logging: 'CLOUD_LOGGING_ONLY'
